version: 0.2

phases:
    
#   # install:
#     # runtime-versions:
#     #   bash: 5
  build:
    commands:
      # Access the branch name from the environment variable
      - BRANCH_NAME=$CODEBUILD_WEBHOOK_HEAD_REF
      - echo $BRANCH_NAME
      # Access the repository name from the environment variable
      - REPO_NAME=$CODEBUILD_SOURCE_REPO_URL
      - echo $REPO_NAME
      # - echo "Branch name: $BRANCH_NAME"
      # - echo "Branch name: $BRANCH_NAME
      # # - echo "my name"
