version: 0.2

phases:
  # install:
    # runtime-versions:
    #   bash: 5
  build:
    commands:
      # Access the branch name from the environment variable
      - BRANCH_NAME=echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F/ '{print $3}')
      # Access the repository name from the environment variable
      - REPO_NAME=echo $CODEBUILD_SOURCE_REPO_URL | awk -F/ '{print $NF}' | sed 's/.git//')
      - echo "Branch name: $BRANCH_NAME"
      - echo "Repository name: $REPO_NAME"
      - echo "my name"
