version: 0.2

phases:  
  # install:
  #   runtime-versions:
  #     bash: 5
  build:
    commands:
      # - git config --global credential.helper '!f() { echo "username=oauth2"; echo "password=$GIT_TOKEN"; }; f'
       - pd=$(pwd)
       - branch=$(aws codepipeline get-pipeline --name $pipeline_name --query pipeline.stages[0].actions[0].configuration.Branch | sed 's/"//g')
       - echo "$branch"
       - cd ..       
       - git config --global credential.helper '!aws codecommit credential-helper $@'
       - git config --global credential.UseHttpPath true
       - git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/$repo_name
       # - git clone $user_name:$password@git-codecommit.us-east-1.amazonaws.com/v1/repos/$repo_name
       # - git clone codecommit::us-east-1://$repo_name
       ## TESTING
       - rm -r $repo_name/*
       - cd $repo_name
       - git checkout $branch || git checkout -b $branch
       - mv "$pd"/* .
       - COMMIT_ID=$(aws codepipeline get-pipeline-execution --pipeline-name $pipeline_name --pipeline-execution-id $AWS_CODEPIPELINE_EXECUTION_ID --query "pipelineExecution.artifactRevisions[0].revisionId" --output text)
       - git add .
       - git config --global user.email "$COMMIT_ID"
       - COMMIT_MESSAGE=$(aws codepipeline get-pipeline-execution --pipeline-name $pipeline_name --pipeline-execution-id $AWS_CODEPIPELINE_EXECUTION_ID --query "pipelineExecution.artifactRevisions[0].revisionSummary" --output text)
       - git commit -m "$COMMIT_MESSAGE"
       - git push https://git-codecommit.us-east-1.amazonaws.com/v1/repos/$repo_name $branch
       - ls
