version: 0.2

phases:
    
#   # install:
#     # runtime-versions:
#     #   bash: 5
  build:
    commands:
      # - git config --global credential.helper '!f() { echo "username=oauth2"; echo "password=$GIT_TOKEN"; }; f'
       - pd=$(pwd)
       - ls
       - cd ..
       - git clone https://sasi_1+1-at-358713093472:QBtFZu+Ep4BIVvRZp+oCg0P7uIWDIDvpHTSXOcYVBWY=@git-codecommit.us-east-1.amazonaws.com/v1/repos/test
       - ls
       # - rm -r test/*
       # - mv "$pd" .
       # - shopt -s extglob  # Enable extended pattern matching
       # - find . -mindepth 1 -maxdepth 1 ! -name 'test' -print0 | cpio -0pd test/
       
       # - cd test
       # - echo "after move"
       # - ls
       # - cat sample.txt
       # # - git checkout -b prod
       # - git add .
       # - git config --global user.email "mahendarreddy.chilumula@gmail.com"
       # - git commit -m "Changes done"
       # - git push https://sasi_1+1-at-358713093472:QBtFZu+Ep4BIVvRZp+oCg0P7uIWDIDvpHTSXOcYVBWY=@git-codecommit.us-east-1.amazonaws.com/v1/repos/test 
